# Generated by Django 5.2.4 on 2025-07-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_likes_comments_delete_blog"),
        ("user", "0002_profile_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.profile"
            ),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=100)),
                ("post_body", models.TextField()),
                ("post_title_color", models.CharField(max_length=15)),
                ("post_img", models.ImageField(upload_to="post_img/")),
                (
                    "post_catagory",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("electronics", "Electronics"),
                            ("life_hacks", "Life Hacks"),
                            ("family", "Family"),
                            ("education", "Education"),
                            ("entertainment", "Entertainment"),
                            ("stories", "Stories"),
                            ("news", "News"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogpost"
            ),
        ),
        migrations.AlterField(
            model_name="likes",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogpost"
            ),
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
