# Generated by Django 5.2 on 2025-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comments_commenter_blogpost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="like",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Likes",
        ),
    ]
