# Generated by Django 5.2 on 2025-07-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_likepost"),
    ]

    operations = [
        migrations.AddField(
            model_name="likepost",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
    ]
